name: CI

on:
  push:
    branches: [ pre ]
  pull_request:
    branches: [ pre ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: |
        npm config set registry https://registry.npmjs.org/
        npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Check formatting
      run: npx prettier --check src/
      
    - name: Build
      run: npm run build
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true 